[package]
name = "normal"
description = "A library used to share tools, utilities and code between our contracts"
version = { workspace = true }
authors = ["jblewnormal <joshua@normalfinance.io"]
repository = { workspace = true }
edition = { workspace = true }
license = { workspace = true }

[features]
testutils = ["soroban-sdk/testutils"]

[dependencies]
soroban-sdk = { workspace = true }
soroban-decimal = { workspace = true }
uint = { version = "0.9.1", default-features = false }
num-traits = "0.2"

[dev-dependencies]
soroban-sdk = { workspace = true, features = ["testutils"] }
test-case = { workspace = true }
